
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module MyComputer(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
//	input 		          		CLOCK2_50,
//	input 		          		CLOCK3_50,
//	input 		          		CLOCK4_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);


	wire [7:0] Dout;
	wire [7:0] IP; // 8-bit IP
	wire [4:0] Debug;
	wire Dval;
	wire Reset_db; // debounced Reset signal
//=======================================================
//  REG/WIRE declarations
//=======================================================
//All push buttons and switches has been debounced in Hardware, below is just a test.

	Debounce Db(.clk(CLOCK_50),.signal_in(SW[9]),.signal_out(Reset_db));
//-------------------------------------------------------------
	CPU MyCPU(.clk(CLOCK_50),.Din(SW[7:0]),.Sample(~KEY[3]),.Btns(~KEY[2:0]),.Reset(Reset_db),
	.Turbo(SW[8]),.Dout(Dout),.Dval(Dval),.GPO(LEDR[5:0]),.Debug(LEDR[9:6]),.IP(IP));

//-------------------------------------------------------------
	Disp2cNum Disnum(.x(Dout),.enable(Dval),.Disp3(HEX3),.Disp2(HEX2),.Disp1(HEX1),.Disp0(HEX0));
//-------------------------------------------------------------
	DispHex DisIP(.IP_num(IP), .Disp5(HEX5), .Disp4(HEX4));
//-------------------------------------------------------------

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//===================synchroniser===========================//
	wire [3:0]syncd_KEY;
	wire [8:0]syncd_SW;

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//=======================================================
//  Structural coding
//=======================================================



endmodule



